[package]
name = "elmesque"
version = "0.1.1"
authors = ["mitchmindtree <mitchell.nordine@gmail.com>"]
description = "An attempt at porting Elm's incredibly useful, purely functional std graphics modules."
readme = "README.md"
keywords = ["elm", "graphics", "2d", "ui", "shape"]
license = "MIT"
repository = "https://github.com/mitchmindtree/elmesque.git"
homepage = "https://github.com/mitchmindtree/elmesque"


[dependencies]
num = "*"
piston2d-graphics = "*"
rand = "*"
rustc-serialize = "*"
vecmath = "*"

[dev-dependencies]
gfx = "0.6.*"
gfx_device_gl = "0.4.*"
piston = "0.1.3"
piston-gfx_texture = "0.1.0"
piston_window = "0.1.0"
piston2d-gfx_graphics = "0.1.22"
pistoncore-glutin_window= "0.1.0"
shader_version = "0.1.0"

